version: '3'

services:
  irpf-2022:
    build:
      context: .
      dockerfile: irpf-2022.dockerfile
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME:/home/irpf
  irpf-2021:
    build:
      context: .
      dockerfile: irpf-2021.dockerfile
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME:/home/irpf
  irpf-2020:
    build:
      context: .
      dockerfile: irpf-2020.dockerfile
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME:/home/irpf
  irpf-2019:
    build:
      context: .
      dockerfile: irpf-2019.dockerfile
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME:/home/irpf
  irpf-2018:
    build:
      context: .
      dockerfile: irpf-2018.dockerfile
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME:/home/irpf
  gcap-2019:
    build:
      context: .
      dockerfile: gcap-2019.dockerfile
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME:/home/gcap
  leao-2019:
    build:
      context: .
      dockerfile: leao-2019.dockerfile
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME:/home/leao
